Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -54,36 +54,36 @@ jobs:
         url="${url}/issues/${issue_num}"
         echo "$url"
 
-        #valid_code=0
-        response_code=$(curl -s -o /dev/null -w "%{http_code}" "$url")
-        if [[ "$TITLE" == *"doc:"* || "$TITLE" == *"docs:"* || "$TITLE" == *"chore:"* ]]; then
-          echo "Skipping validation as this is a PR for documentation or chore."
-          gh pr edit $PRNUM --remove-label "PR: Issue-verification-failed"
-          gh pr edit $PRNUM --remove-label "PR:Ready-to-Review"
-          exit 0
-        elif [[ "$response_code" -eq 200 ]]; then
-          # Check if issue is open or closed
-          text=$(curl -s "$url")
-          echo "$text"
-          echo "checking status of the issue"
-          if [[ $(echo "$text" | jq -r '.state') == "open" ]]; then
-            echo "Issue #$issue_num is open"
-            echo "Issue reference found in the pull request body."
-            gh pr edit $PRNUM --remove-label "PR: Issue-verification-failed"
-            gh pr edit $PRNUM --add-label "PR:Ready-to-Review"
-            exit 0
-          else
-            echo "Issue #$issue_num is not open"
-            exit 1
-          fi
-        else
-            echo "Invalid Response Code obtained - error code: $response_code"
-            echo "No valid issue reference found in the pull request body."
-            gh pr comment $PRNUM --body "PR is not linked to any issue, please make the corresponding changes in the body."
-            gh pr edit $PRNUM --add-label "PR: Issue-verification-failed"
-            gh pr edit $PRNUM --remove-label "PR:Ready-to-Review"
-            exit 1
-        fi
+        # valid_code=0
+        # response_code=$(curl -s -o /dev/null -w "%{http_code}" "$url")
+        # if [[ "$TITLE" == *"doc:"* || "$TITLE" == *"docs:"* || "$TITLE" == *"chore:"* ]]; then
+        #   echo "Skipping validation as this is a PR for documentation or chore."
+        #   gh pr edit $PRNUM --remove-label "PR: Issue-verification-failed"
+        #   gh pr edit $PRNUM --remove-label "PR:Ready-to-Review"
+        #   exit 0
+        # elif [[ "$response_code" -eq 200 ]]; then
+        #   # Check if issue is open or closed
+        #   text=$(curl -s "$url")
+        #   echo "$text"
+        #   echo "checking status of the issue"
+        #   if [[ $(echo "$text" | jq -r '.state') == "open" ]]; then
+        #     echo "Issue #$issue_num is open"
+        #     echo "Issue reference found in the pull request body."
+        #     gh pr edit $PRNUM --remove-label "PR: Issue-verification-failed"
+        #     gh pr edit $PRNUM --add-label "PR:Ready-to-Review"
+        #     exit 0
+        #   else
+        #     echo "Issue #$issue_num is not open"
+        #     exit 1
+        #   fi
+        # else
+        #     echo "Invalid Response Code obtained - error code: $response_code"
+        #     echo "No valid issue reference found in the pull request body."
+        #     gh pr comment $PRNUM --body "PR is not linked to any issue, please make the corresponding changes in the body."
+        #     gh pr edit $PRNUM --add-label "PR: Issue-verification-failed"
+        #     gh pr edit $PRNUM --remove-label "PR:Ready-to-Review"
+        #     exit 1
+        # fi
         
         # echo "Valid flag is: $valid_code"
         # echo "Valid flag is: $response_code"
